/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Visao.*;
import Controle.ConectaBanco;
import Controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author euris
 */
public class TransferenciaBancaria extends javax.swing.JDialog {
    ConectaBanco conexao = new ConectaBanco();
    
    String SQL_consultaGeneria = "SELECT * FROM BANCO";
    
    ConsultaBanco consultaBanco;
    String jtDS_Banco = null;
    float saldo;
    
    /**
     * Creates new form ConsultaCCusto
     */
    public TransferenciaBancaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        conexao.conecta();
        initComponents();
        preencherTabela(SQL_consultaGeneria);
        consultaBanco = new ConsultaBanco(new javax.swing.JFrame(), true);
        //Abrir o frame centralizado
        setLocationRelativeTo(null);
    }
    
    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"Código","Descrição","Valor"};
    
        conexao.executaSQL(SQL);
        try {
            conexao.rs.first();
            do{ 
                dados.add(new Object[]{conexao.rs.getString("CD_BANCO"),
                                       conexao.rs.getString("DS_BANCO"),
                                       conexao.rs.getString("VL_SALDO")});
            }while(conexao.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList da consulta do Banco. \nErro: "+ ex);
        }
       
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);//Monta a tabela
        jTableConsulta.setModel(modelo);
        jTableConsulta.getColumnModel().getColumn(0).setPreferredWidth(50);//Largura da coluna
        jTableConsulta.getColumnModel().getColumn(0).setResizable(false);
        jTableConsulta.getColumnModel().getColumn(1).setPreferredWidth(330);//Largura da coluna
        jTableConsulta.getColumnModel().getColumn(1).setResizable(false);
        jTableConsulta.getColumnModel().getColumn(2).setPreferredWidth(250);//Largura da coluna
        jTableConsulta.getColumnModel().getColumn(2).setResizable(false);
        jTableConsulta.getTableHeader().setReorderingAllowed(false);// Para a tabela não ser reorganizada
        jTableConsulta.setAutoResizeMode(jTableConsulta.AUTO_RESIZE_OFF);// Parametros de seleção
        jTableConsulta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);// Parametros de seleção
    }
    
    public void limpa_campo(){
        jTextFieldCodBanco.setText("");
        jTextFieldDsBanco.setText("");
        jTextFieldCodBanco1.setText("");
        jTextFieldDsBanco1.setText("");    
        jTextFieldVlTransferencia.setText("");
    }
    
    public void transferir(int codBanco1, int codBanco2, float valor){
        conexao.executaSQL("SELECT VL_SALDO FROM BANCO WHERE CD_BANCO = "+codBanco1+";");
        try {
            conexao.rs.first();
            do{ 
                saldo = Float.parseFloat(conexao.rs.getString("VL_SALDO"));
            }while(conexao.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar o saldo da conta. \nErro: "+ ex);
        }
        
        if((saldo - valor) < 0){
            JOptionPane.showMessageDialog(null, "Não é posível realizar essa transferência, o valor R$ "+valor+" é maior que o saldo da conta.");
        }else{
            String SQL1 = "UPDATE BANCO SET VL_SALDO = (SELECT VL_SALDO + "+valor+" FROM BANCO WHERE CD_BANCO = "+codBanco2+") WHERE CD_BANCO = "+codBanco2+";";
            String SQL2 = "UPDATE BANCO SET VL_SALDO = (SELECT VL_SALDO - "+valor+" FROM BANCO WHERE CD_BANCO = "+codBanco1+") WHERE CD_BANCO = "+codBanco1+";";
            conexao.executaSqlUpdate(SQL1);
            conexao.executaSqlUpdate(SQL2);
            JOptionPane.showMessageDialog(null, "Saldo transferido com sucesso.");
            limpa_campo();
        }
    }
    public boolean verificaCampo(){
        if(jTextFieldCodBanco.getText().isEmpty() || jTextFieldDsBanco1.getText().isEmpty()||
           jTextFieldVlTransferencia.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jButtonTransferir = new javax.swing.JButton();
        jTextFieldCodBanco = new javax.swing.JTextField();
        jTextFieldDsBanco = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldDsBanco1 = new javax.swing.JTextField();
        jTextFieldCodBanco1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldVlTransferencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MenuLogo.setBackground(new java.awt.Color(47, 79, 79));
        MenuLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        MenuLogo.setToolTipText("");
        MenuLogo.setPreferredSize(new java.awt.Dimension(2, 82));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transferência Bancária");

        javax.swing.GroupLayout MenuLogoLayout = new javax.swing.GroupLayout(MenuLogo);
        MenuLogo.setLayout(MenuLogoLayout);
        MenuLogoLayout.setHorizontalGroup(
            MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLogoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLogoLayout.setVerticalGroup(
            MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jButtonTransferir.setText("Transferir");
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });

        jTextFieldCodBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodBancoKeyPressed(evt);
            }
        });

        jTextFieldDsBanco.setEditable(false);
        jTextFieldDsBanco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDsBancoFocusGained(evt);
            }
        });

        jLabel39.setText("Codigo:     Banco:");

        jTextFieldDsBanco1.setEditable(false);
        jTextFieldDsBanco1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDsBanco1FocusGained(evt);
            }
        });

        jTextFieldCodBanco1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodBanco1KeyPressed(evt);
            }
        });

        jLabel40.setText("Codigo:     Banco:");

        jLabel2.setText("Valor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonTransferir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jTextFieldDsBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodBanco1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jTextFieldDsBanco1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldVlTransferencia))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDsBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDsBanco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldVlTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldCodBanco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransferir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        
    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        if(verificaCampo() == true){
            transferir(Integer.parseInt(jTextFieldCodBanco.getText()), 
                       Integer.parseInt(jTextFieldCodBanco1.getText()), 
                       Float.parseFloat(jTextFieldVlTransferencia.getText()));
        }else{
            JOptionPane.showMessageDialog(null, "Preencher todos os campos.");
        }
        preencherTabela(SQL_consultaGeneria);
    }//GEN-LAST:event_jButtonTransferirActionPerformed

    private void jTextFieldCodBancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodBancoKeyPressed
        if(evt.getKeyCode() == evt.VK_F9){
            consultaBanco.setVisible(true);
            jTextFieldCodBanco.setText(this.consultaBanco.getCodigo());
            jtDS_Banco = this.consultaBanco.getDescricao();
        }
    }//GEN-LAST:event_jTextFieldCodBancoKeyPressed

    private void jTextFieldDsBancoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDsBancoFocusGained
        jTextFieldDsBanco.setText(jtDS_Banco);
    }//GEN-LAST:event_jTextFieldDsBancoFocusGained

    private void jTextFieldDsBanco1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDsBanco1FocusGained
        jTextFieldDsBanco1.setText(jtDS_Banco);
    }//GEN-LAST:event_jTextFieldDsBanco1FocusGained

    private void jTextFieldCodBanco1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodBanco1KeyPressed
        if(evt.getKeyCode() == evt.VK_F9){
            consultaBanco.setVisible(true);
            jTextFieldCodBanco1.setText(this.consultaBanco.getCodigo());
            jtDS_Banco = this.consultaBanco.getDescricao();
        }
    }//GEN-LAST:event_jTextFieldCodBanco1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferenciaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferenciaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferenciaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferenciaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransferenciaBancaria dialog = new TransferenciaBancaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuLogo;
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldCodBanco;
    private javax.swing.JTextField jTextFieldCodBanco1;
    private javax.swing.JTextField jTextFieldDsBanco;
    private javax.swing.JTextField jTextFieldDsBanco1;
    private javax.swing.JTextField jTextFieldVlTransferencia;
    // End of variables declaration//GEN-END:variables
}
